name: buildArm
on:
  push:
  pull_request:

env:
  LIBGDIPLUS_VERSION: '6.0.5'

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install autotools
        run: 
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          /opt/homebrew/bin/brew install autoconf automake libtool pkg-config

      - name: Download sources, install dependencies
        run: |
          cd runtime.osx.10.10-x64.CoreCompat.System.Drawing
          git clone https://github.com/mono/libgdiplus --depth 1 --single-branch --branch ${LIBGDIPLUS_VERSION}
          /opt/homebrew/bin/brew install libtiff giflib libjpeg glib cairo freetype fontconfig libpng

      - name: Build
        run: |
          cd runtime.osx.10.10-x64.CoreCompat.System.Drawing

          # libffi is keg-only
          export LDFLAGS="-L/opt/homebrew/opt/libffi/lib"
          export PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig"

          ./build.sh
          mkdir ${{ github.workspace }}/bin/
          dotnet build -c Release /p:Version=${LIBGDIPLUS_VERSION}.${GITHUB_RUN_NUMBER}
          dotnet pack -c Release /p:Version=${LIBGDIPLUS_VERSION}.${GITHUB_RUN_NUMBER} -o ${{ github.workspace }}/bin/

      - name: Upload NuGet package
        uses: actions/upload-artifact@v2
        with:
          name: libgdiplus
          path: |
            ${{ github.workspace }}/bin/

  test:
    runs-on: macOS-11
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v2
        with:
          name: libgdiplus
          path: |
            ${{ github.workspace }}/bin/

      - name: Clean dependencies
        run: |
          /opt/homebrew/bin/brew remove --force $(brew list)

          echo
          echo "=========================="
          echo "Contents of /opt/homebrew/opt"
          echo "=========================="
          echo

          ls -l /opt/homebrew/opt/

      - name: Test
        run: |
          cd runtime.osx.10.10-x64.CoreCompat.System.Drawing.Tests

          dotnet nuget list source
          dotnet nuget add source ${{ github.workspace }}/bin/ -n ci

          dotnet add package runtime.osx.10.10-x64.CoreCompat.System.Drawing --version ${LIBGDIPLUS_VERSION}.${GITHUB_RUN_NUMBER}
          dotnet test
